global:
  pattern: common
  valuesDirectoryURL: https://github.com/pattern-clone/common/raw/main
  options:
    useCSV: True
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: example
  isHubCluster: true

#  managedClusterGroups:
#  - name: factory
#    # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#    # Location of values-global.yaml, values-{name}.yaml, values-{app}.yaml
#    # valuesDirectoryURL: https://github.com/dagger-refuse-cool/edge-gitops/raw/main/
#    targetRevision: main
#    path: applications/factory
#    helmOverrides:
#    - name: clusterGroup.isHubCluster
#      value: false
#    clusterSelector:
#      matchExpressions:
#      - key: vendor
#        operator: In
#        values:
#          - OpenShift
#
#  namespaces:
#  - open-cluster-management
#
#  subscriptions:
#  - name: advanced-cluster-management
#    namespace: open-cluster-management
#    source: redhat-operators
#    channel: release-2.3
#    csv: v2.3.2
#
#  projects:
#  - datacenter
# 
#  applications:
#  - name: acm
#    namespace: default
#    project: datacenter
#    path: applications/acm
