global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: example

  namespaces:
  - open-cluster-management
  - application-ci

  subscriptions:
  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.3
    csv: advanced-cluster-management.v2.3.2

  - name: openshift-pipelines-operator-rh
    csv: redhat-openshift-pipelines.v1.5.1

  projects:
  - datacenter
 
  applications:
  - name: acm
    namespace: open-cluster-management
    project: datacenter
    path: common/acm
    ignoreDifferences:
    - group: internal.open-cluster-management.io
      kind: ManagedClusterInfo
      jsonPointers:
      - /spec/loggingCA

  - name: pipelines
    namespace: application-ci
    project: datacenter
    path: charts/datacenter/pipelines

  managedClusterGroups:
  - name: edge
    # Optional - Point to a different repo
    # repoURL: https://github.com/dagger-refuse-cool/mySite.git
    # Must contain values-{clustergroupname}.yaml at the top level
    targetRevision: main
    helmOverrides:
    # Values must be strings!
    - name: clusterGroup.isHubCluster
      value: "false"
    clusterSelector:
#      matchLabels:
#        clusterGroup: factory
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

